### ISSUE TITLE
无法更改语言文件

### ISSUE THREAD

**Issue by yasdiox** [GoldenPotato137/OxygenSystem#8]
语言文件改完后重启就会恢复原样，如果创建新的文件就会报错。

`[14:25:40 ERROR]: Error occurred while enabling OxygenSystem v1.2.1 (Is it up to date?)
java.lang.IllegalArgumentException: The embedded resource 'message_zh-TW.yml' cannot be found in plugins\OxygenSystem-1.2.1.jar
        at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:193) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at cn.goldenpotato.oxygensystem.Config.MessageManager.LoadMessage(MessageManager.java:15) ~[OxygenSystem-1.2.1.jar:?]
        at cn.goldenpotato.oxygensystem.OxygenSystem.Load(OxygenSystem.java:77) ~[OxygenSystem-1.2.1.jar:?]
        at cn.goldenpotato.oxygensystem.OxygenSystem.onEnable(OxygenSystem.java:30) ~[OxygenSystem-1.2.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1611]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1611]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[purpur-1.18.2.jar:git-Purpur-1611]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.18.2.jar:git-Purpur-1611]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1611]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1611]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1611]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by yasdiox** [comment]
通过改jar里的语言文件成功了

**Comment by GoldenPotato137** [comment]
是的，正如报错所述，我们目前没有提供繁体中文的翻译。
然后关于重启后回复原样，那是一个设计问题，这个问题会在几天内的更新中一起被修复。
非常感谢您的反馈。
